import time
import os

# As you can see, its not very optimal 
def frame1():
    print("                 ***            ")

def frame2():
    print("                 ***            ")
    print("                 ***            ")

def frame3():
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame4(): 
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")
def frame5():
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")
def frame6():
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame7():
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame8():
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")
  
def frame9():
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")
def frame10():
    print("              * * * * *         ")
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")
def frame11():
    print("               * * * *          ")
    print("              * * * * *         ")
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame12():
    print("                * * *           ")
    print("               * * * *          ")
    print("              * * * * *         ")
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame13():
    print("                 * *            ")
    print("                * * *           ")
    print("               * * * *          ")
    print("              * * * * *         ")
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

def frame14():
    print("                  *             ")
    print("                 * *            ")
    print("                * * *           ")
    print("               * * * *          ")
    print("              * * * * *         ")
    print("             * * * * * *        ")
    print("            * * * * * * *       ")
    print("           * * * * * * * *      ")
    print("          * * * * * * * * *     ")
    print("         * * * * * * * * * *    ")
    print("        * * * * * * * * * * *   ")
    print("       * * * * * * * * * * * *  ")
    print("                 ***            ")
    print("                 ***            ")

os.system("clear")
time.sleep(.1)
frame1()
time.sleep(.5)
os.system("clear")
frame2()
time.sleep(.5)
os.system("clear")
frame3()
time.sleep(.5)
os.system("clear")
frame4()
time.sleep(.5)
os.system("clear")
frame5()
time.sleep(.5)
os.system("clear")
frame6()
time.sleep(.5)
os.system("clear")
frame7()
time.sleep(.5)
os.system("clear")
frame8()
time.sleep(.5)
os.system("clear")
frame9()
time.sleep(.5)
os.system("clear")
frame10()
time.sleep(.5)
os.system("clear")
frame11()
time.sleep(.5)
os.system("clear")
frame12()
time.sleep(.5)
os.system("clear")
frame13()
time.sleep(.5)
os.system("clear")
frame14()
time.sleep(.5)
os.system("clear")
print("Yay!")
time.sleep(1.5)
os.system("clear")
